<TextInputWidget>:
    canvas:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            pos: self.pos
            size: self.size

    TextInput:
        text: 'cocpy.com'
        pos: 10, 100
        halign: 'center'
        on_state:
    Button:
		text: "Btn0"
		background_color: 1, 1, 1, 1
		font_size: 20

    TextInput:
        text: 'first'
        pos: 400, 180
        readonly: True
